trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master
  paths:
    exclude:
    - '*.md'

name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

variables:
- group: tttemplate01
- name: MAJOR_MINOR_VERSION
  value: "0.1" # update between releases
- name: SEMANTIC_VERSION
  value: "$(MAJOR_MINOR_VERSION).$(Build.BuildId)"
- name: KUSTO_DB
  value: "build$(Build.BuildId)"
- name: ACR_NAME
  value: tttemplate01
- name: ACR_PULL_SERVICE_CONNECTION
  value: Terraform
- name: ACR_PUSH_SERVICE_CONNECTION
  value: Terraform
- name: AKS_NAME
  value: tttemplate01
- name: AKS_SP_CLIENT_ID
  value: cd0ad856-af8e-424e-b935-ce7ad6da5c9d
#- name: AKS_SP_CLIENT_SECRET
#  value: ENTER
- name: AKS_VERSION
  value: 1.15.7
- name: CHART_NAME
  value: contoso
- name: HELM_VERSION
  value: 3.1.2
- name: KUSTO_NAME
  value: tttemplate01
- name: RESOURCE_GROUP
  value: dataops2-tf
- name: TENANT_ID
  value: 72f988bf-86f1-41af-91ab-2d7cd011db47
- name: TERRAFORM_SERVICE_CONNECTION
  value: Terraform
- name: TERRAFORM_STORAGE_ACCOUNT
  value: tttemplate01terraform
- name: VNET_NAME
  value: tttemplate01

pool:
  vmImage: ubuntu-latest


jobs:
- template: infrastructure/ci-cd-pipeline.yml
