trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master
  paths:
    exclude:
    - '*.md'

name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

variables:
- group: terraform-aspnet-devops-template
# should contain variables
# - APP_NAME (short globally unique name, e.g. "starterterraform")
# - AGENT_POOL_MANAGEMENT_TOKEN
# - AKS_SP_CLIENT_SECRET
# - TERRAFORM_SP_CLIENT_SECRET
- name: MAJOR_MINOR_VERSION
  value: "0.1" # update between releases
- name: SEMANTIC_VERSION
  value: "$(MAJOR_MINOR_VERSION).$(Build.BuildId)"
- name: ACR_NAME
  value: $(APP_NAME)aspnetmplt
- name: TERRAFORM_SP_CLIENT_ID
  value: 4074cb3c-3797-4596-8031-22fc03770b84
- name: AKS_SP_CLIENT_ID
  value: 4c90a2fe-7261-475a-ae98-a6acfbcc5d17
- name: AKS_SP_OBJECT_ID
  value: 235c67ad-81ff-4c43-bda8-b5f1b9120a77
- name: AKS_VERSION
  value: 1.15.7
- name: HELM_RELEASE_NAME
  value: contoso
- name: RESOURCE_GROUP
  value: aspnetmplt
- name: ARM_SUBSCRIPTION_ID
  value: f3414c2e-c479-484b-b19e-1787de6e0140
- name: ARM_TENANT_ID
  value: 72f988bf-86f1-41af-91ab-2d7cd011db47
- name: TERRAFORM_SERVICE_CONNECTION
  value: Terraform
- name: TERRAFORM_STORAGE_ACCOUNT
  value: $(APP_NAME)terraform
- name: AGENT_POOL_NAME
  value: aspnetmplt
- name: JMETER_VERSION
  value: 5.1.1
# Enable buildkit to speed up multi-stage pipeline builds (avoid running unit tests twice)
- name: DOCKER_BUILDKIT
  value: 1

pool:
  vmImage: ubuntu-latest


jobs:
- template: infrastructure/ci-cd-pipeline.yml
