trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master
  paths:
    exclude:
    - '*.md'

name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

variables:
- name: MAJOR_MINOR_VERSION
  value: "0.1" # update between releases
- name: SEMANTIC_VERSION
  value: "$(MAJOR_MINOR_VERSION).$(Build.BuildId)"
- name: KUSTO_DB
  value: "build$(Build.BuildId)"

stages:
- template: infrastructure/ci-cd-pipeline.yml
