steps:

- task: HelmInstaller@1
  displayName: Install helm
  inputs:
    helmVersionToInstall: $(HELM_VERSION)

- task: KubectlInstaller@0
  displayName: Install kubectl
  inputs:
    kubectlVersion: $(AKS_VERSION)

- task: AzureCLI@1
  displayName: Login to AKS
  inputs:
    azureSubscription: $(TERRAFORM_SERVICE_CONNECTION)
    scriptLocation: inlineScript
    inlineScript: |
      set -eux  # fail on error
      az aks get-credentials -g "$RESOURCE_GROUP" -n "$AKS_NAME" -f kube_config
      echo "##vso[task.setvariable variable=KUBE_CONFIG]$PWD/kube_config"
