steps:

- task: HelmInstaller@1
  displayName: Install helm
  inputs:
    helmVersionToInstall: $(HELM_VERSION)

- task: KubectlInstaller@0
  displayName: Install kubectl
  inputs:
    kubectlVersion: $(AKS_VERSION)
