parameters:
  TerraformVersion: 0.12.24
  TerraformStateKey:

steps:

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
  displayName: Install Terraform
  inputs:
    terraformVersion: ${{ parameters.TerraformVersion }}

- bash: |
    set -eux  # fail on error
    terraform init \
      -backend-config=storage_account_name=$(TERRAFORM_STORAGE_ACCOUNT) \
      -backend-config=container_name=terraformstate \
      -backend-config=key=${{ parameters.TerraformStateKey }}.tfstate \
      -backend-config=resource_group_name=$(RESOURCE_GROUP) \
  workingDirectory: $(TERRAFORM_DIRECTORY)
  displayName: Terraform init
