parameters:
  provisionStorage: false
  TerraformVersion: 0.12.24
  TerraformStateKey:
  TerraformDirectory: $(TERRAFORM_DIRECTORY)
  TerraformEnvironmentServiceConnection: $(TERRAFORM_SERVICE_CONNECTION)
  TerraformBackendResourceGroup: $(RESOURCE_GROUP)
  TerraformBackendStorageAccount: $(TERRAFORM_STORAGE_ACCOUNT)
  TerraformBackendStorageContainer: terraformstate
  TerraformBackendLocation: North Europe
  TerraformSubscriptionId: $(SUBSCRIPTION_ID)
  TerraformTenantId: $(TENANT_ID)
  TerraformServicePrincipalId: $(TERRAFORM_SP_CLIENT_ID)
  TerraformServicePrincipalKey: $(TERRAFORM_SP_CLIENT_SECRET)

steps:

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
  displayName: Install Terraform
  inputs:
    terraformVersion: ${{ parameters.TerraformVersion }}

- bash: |
    set -eux  # fail on error
    terraform init \
      -backend-config=storage_account_name=${{ parameters.TerraformBackendStorageAccount }} \
      -backend-config=container_name=${{ parameters.TerraformBackendStorageContainer }} \
      -backend-config=key=${{ parameters.TerraformStateKey }}.tfstate \
      -backend-config=resource_group_name=${{ parameters.TerraformBackendResourceGroup }} \
      -backend-config=subscription_id=${{ parameters.TerraformSubscriptionId }} \
      -backend-config=tenant_id=${{ parameters.TerraformTenantId }} \
      -backend-config=client_id=${{ parameters.TerraformServicePrincipalId }} \
      -backend-config=client_secret=${{ parameters.TerraformServicePrincipalKey }}
  workingDirectory: ${{ parameters.TerraformDirectory }}
  displayName: Terraform init
